- hosts: localhost
  tasks:
        - name: Include credentials file(vault)
          include_vars: credentials.yml

        - name: Provison ec2 instances for Windows Worker Node
          ec2:
            image: "ami-0f7c1f6f84b14d7d6"
            instance_type: "t2.medium"
            key_name: "ec2_os1"
            wait: yes
            count: 1
            state: present
            region: "ap-south-1"
            vpc_subnet_id: "subnet-0f7a7f67"
            group_id: "sg-0d301d8b5d2ad3990"
            assign_public_ip: yes
            user_data: |
                       <powershell>
                       $admin = [adsi]("WinNT://./administrator, user")
                       $admin.PSBase.Invoke("SetPassword", "Password123!")
                       Invoke-Expression ((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))
                       Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
                       Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
                       Start-Service sshd
                       Set-Service -Name sshd -StartupType 'Automatic'
                       New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
                       </powershell>
            instance_tags:
              Name: WindowsWorkerNode
            aws_access_key: "{{ user }}"
            aws_secret_key: "{{ paswd }}"
          register: ec2
        - name: Add new instance to host group
          add_host:
            name: win-temp-{{ item.public_ip }}
            ansible_ssh_host: "{{ item.public_ip }}"
            groupname: win
          loop: "{{ ec2.instances }}"

        - name: wait for WinRM to answer on all hosts
          wait_for:
            port: 5986
            host: "{{ item.public_ip }}"
            timeout: 300
          with_items: "{{ ec2.instances }}"


- hosts: win
  gather_facts: no
  tasks:
        - name: Install Containers
          win_feature:
            name: containers
            state: present
        - name: Download wins, kubelet, and kubeadm
          win_shell: curl.exe -LO https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/PrepareNode.ps1
        - name: Install wins, kubelet, and kubeadm
          win_shell: .\PrepareNode.ps1 -KubernetesVersion v1.21.0
        - name: Join to Master Node
          win_shell: "{{ lookup('file', '/token.txt') }}"        
